name: Build sierra

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: gentoo/stage3:latest

    steps:
      - name: Checkout sierra sources
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          export FEATURES="-network-sandbox -ipc-sandbox -mount-sandbox" # docker

          emerge-webrsync -q
          getuto
          emerge -qgn app-admin/setools sys-apps/policycoreutils sys-apps/secilc

      - name: Generate configure script
        run: autoreconf --install

      - name: Configure sierra
        run: ./configure

      - name: Build monolithic policy
        run: make
